openapi: 3.0.0
info:
  tags:
    - overview
  title: 'Invoice Ninja API Reference.'
  description: "![](https://i.ibb.co/v3Yt03v/todo-api-background.png)\n\n## \U0001F4AB Overview\n\nTo Do API provides a simple way for people to manage their tasks and plan their day. This API can be used to create mobile and web applications.This API is documented using **OpenAPI 3.0**. The implementation lives in this [GitHub repo](https://github.com/stoplightio/studio-demo/blob/master/reference/todos/todo.v1.yaml).\n\n### \U0001F9F0 Cross-Origin Resource Sharing\nThis API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/). CORS support is necessary to make calls from the request maker within the API docs.\n\n### \U0001F3C1 Trying out your own API Specification\nElements can be used to generate API docs for any OpenAPI document. Replace this OpenAPI with a URL to your own OpenAPI document to get started."
  termsOfService: 'https://invoiceninja.github.io/docs/legal/terms_of_service/#page-content'
  contact:
    email: contact@invoiceninja.com
    name: Invoice Ninja Support
    url: 'https://www.invoiceninja.com'
  license:
    name: 'Elastic License'
    url: 'https://www.elastic.co/licensing/elastic-license'
  version: 5.9.2
servers:
  - title: demo
    url: 'https://demo.invoiceninja.com'
    description: |
          ## Demo API endpoint 
          You can use the demo API key `TOKEN` to test the endpoints from within this API spec
  - title: production
    url: 'https://invoicing.co'
    description: |
          ## Production API endpoint